### ISSUE TITLE
Module00

### ISSUE THREAD

**Issue by Rui-Pedro-Pires** [SEAME-pt/SEAME-WarmUp-24-25-Team02#1]
# EPIC

- [ ] SEAME-pt/SEAME-WarmUp-24-25#54  

# Description

## Exercise 00 : Welcome to SEA:ME

> Let’s explore the world of [SEA:ME](https://github.com/SEA-ME)!
* Follow this:
    1. Do you have a GitHub account? If not, create one.
    2. Fork [SEA:ME Students](https://github.com/SEA-ME/SEA-ME-Students) from [SEA:ME](https://github.com/SEA-ME). Make sure you see all the branches!
    3. Clone forked repository
    4. Create a folder inside your cloned repo by the unique id generated as per following rule: 
        - If your full name is Jack Moon (FirstName: Jack, LastName: Moon), then your unique id would be jmoon (first letter of your first name followed by your lastname)
    5. Create a markup file by the same name as the folder: uniquename.md inside the folder
        - If your id is jmoon, then the file would be jmoon.md
    6. Fill in the information about yourself. (Use Template_Student_Bio.md file for reference):
    7. Save the changes.
    8. git add, git commit, git push
    9. Create a merge request (MR) to the MainJuly2024 branch in original repo of SEA:ME
    10. Do you know what you just did?

* Now for every project, remember to do following:
  - Fork the main project repo from SEA:ME
  - Work out and save all your work in the forked repo
  - Once done, provide us the links to your repo and evaluation form in your own [SEA:ME Students](https://github.com/SEA-ME/SEA-ME-Students) profile

## Exercise 01 : Don't you wish your framework was Qt like you?
> Let’s find out what is Qt!
<aside>
💡 Install Qt. You always go for an LTS version!
</aside>

## Exercise 02 : Do you know string??
> How deeply do you know about C++? Let’s start from the beginning again.
The first one is just for using string. 

- Make the program as follows this:
    1. Use simple string class
        1. To convert UPPER CASE
        2. To convert LOWER CASE
    2. Use string class’s functions
        1. substr, append, insert, replace, erase, etc..
    - The program gets two arguments:
        - ./convert {command} {string}
            - ex) `./convert up I’m the one!`
                - output:  `I’M THE ONE!`
            - ex) `./convert down I’m A SMall man`
                - output: `i’m a small man`

## Exercise 03 : Old PhoneBook

> Our older computers have no graphics. They only could use characters on the black screen. Can you imagine? No graphics, No mouse. You don’t need to imagine it. Because now you will make yourself!

- You have to make a Phonebook application.  Follow the details:
    - User can use these commands
        - ADD
            - Add new contact in phonebook
            - Require contents
                1. Name
                2. Phone number(unique)
                3. Nickname
        - SEARCH
            - List up the contacts with index
                1. User choose index display details of the contact.
                2. If user want can bookmark the contact
        - REMOVE
            - Remove a contact with an index or a phone number.
        - BOOKMARK
            - List up the bookmarked contact
        - EXIT
            - Shut down the program
<aside>
💡 Try to make good use of the class.
</aside>

## TASKS

- [ ] SEAME-pt/SEAME-WarmUp-24-25#12 
- [ ] SEAME-pt/SEAME-WarmUp-24-25#13 
- [ ] SEAME-pt/SEAME-WarmUp-24-25#14 
- [ ] SEAME-pt/SEAME-WarmUp-24-25#44
