### ISSUE TITLE
GitHub: CD/CI infrastructure and pipeline

### ISSUE THREAD

**Issue by luis-ffe** [SEAME-pt/SEAME-WarmUp-24-25-Team02#14]
# EPIC

- [ ] SEAME-pt/SEAME-WarmUp-24-25#54

# Description

General research and understanding of GitHub capabilities for CD/CI such as:
- Version control.
- GitHub Actions.
- GitHub Agents
- Unit Testing.
- Automated Testing, Self-Hosted and cloud-hosted machine environments.
- Project: use of Scrum and Agile methodology

## TASKS

- [ ] SEAME-pt/SEAME-WarmUp-24-25-Team02#7
- [ ] SEAME-pt/SEAME-WarmUp-24-25-Team02#12
- [ ] SEAME-pt/SEAME-WarmUp-24-25-Team02#10 
- [ ] SEAME-pt/SEAME-WarmUp-24-25-Team02#9
