### ISSUE TITLE
QT: CD/CI infrastructure and pipeline

### ISSUE THREAD

**Issue by luis-ffe** [SEAME-pt/SEAME-WarmUp-24-25-Team02#18]
# EPIC

- [ ] SEAME-pt/SEAME-WarmUp-24-25-Team02#17 

# Description

Setup, installation and getting a general understanding of the QT IDE environment and projects:

## TASKS

- [ ] SEAME-pt/SEAME-WarmUp-24-25#52
- [ ] SEAME-pt/SEAME-WarmUp-24-25#53
